### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by cheesits456** [ihaveamac/faketik#1]
It would be sweet if this app could also create tickets for DSiWare

**Comment by ihaveamac** [comment]
It already does this, unless you can demonstrate a situation where it didn't?

**Comment by cheesits456** [comment]
I had to restore a backup of CTRNAND, so I lost all the tickets for the apps I had installed. I found this app, so I downloaded it and ran it, and all my 3ds titles appeared on my home screen again, but none of the DSi titles. I verified that the titles were installed by checking TWLN, and they were all there. Any idea why it didn't install tickets for the DSi apps?

**Comment by ihaveamac** [comment]
It can only create tickets for titles that are considered "installed". For DSiWare, this is likely stored in title.db in CTRNAND. Because an older version was restored, the system does not know that these titles exist, therefore faketik will not find them.

**Comment by ihaveamac** [comment]
The reason this didn't happen to SD titles is because title.db is also stored on the SD card. The easiest method to fix missing DSiWare titles is to back up save files from twln and re-install.

**Comment by cheesits456** [comment]
ah okay, that makes sense. The way i worked around it was going into TWLN from GodMode9 and then I just packaged all the DSi apps to a CSI file, then I used FBI to install them all, and now they're all there

**Comment by ihaveamac** [comment]
README will be updated containing information on missing titles.
