### ISSUE TITLE
Faketik crashes every time I launch?

### ISSUE THREAD

**Issue by TGGAAGEERS** [ihaveamac/faketik#2]
When launching Faketik from the homebrew launcher, my system crashes with the error “An exception occurred”. I’ve tried a few times with the same result each time. I’m on the latest version of Luma3DS

**Comment by TGGAAGEERS** [comment]
![This is the error I get when my 3DS crashes](https://user-images.githubusercontent.com/17342634/82853438-09e47580-9ec3-11ea-8e48-157be363a456.jpg)

**Comment by TGGAAGEERS** [comment]
Nvm, it crashed on v1.1.1 every time. Downloaded v1.1.0 and it worked just fine

**Comment by ihaveamac** [comment]
Please try 1.1.1 again and send me the crash dump.

If this is an issue with the latest release this issue should stay open.
