### ISSUE TITLE
Crear un titulo "Fake" para "Health and Safety"

### ISSUE THREAD

**Issue by wuniversales** [ihaveamac/faketik#3]
Hola, os comento...
Quiero eliminar el programita "Health and Safety", pero por lo que veo cada vez que lo elimino la store me pide actualizar la consola....
¿Seria posible crear un "Fake" para esa aplicación?
Algo así como dejar solo el ticket instalado, pero invisible, para que no se vea..
Gracias y Saludos :)

**Comment by FrozenChen** [comment]
Para esto se necesita un titulo que reemplace health and safety que tenga un icono oculto, de todos modos esto no es algo que faketik puede hacer ni es su proposito
