### ISSUE TITLE
Failed to query external title database?

### ISSUE THREAD

**Issue by rankle258** [ihaveamac/faketik#4]
Everything on my home menu disappeared after a crash on Twilight Menu++, am trying to use this to get all my titles to re-appear and I'm getting this error?
![IMG-5321](https://user-images.githubusercontent.com/88335546/127885726-8b1e1f58-442f-4866-a0b8-696e43ec2525.jpg)

**Comment by ihaveamac** [comment]
This likely means something happened to title.db and it needs to be rebuilt. There are currently no automated tools to do this, but you can use https://github.com/ihaveamac/rebuild-title-database for this:

1. Overwrite it with a clean title.db using fix-titledb.py
2. Run rebuild-title-database.py to generate all the title info entries
3. Use https://github.com/wwylele/save3ds to import all the files from above into the new title.db

If you don't know how to do this or aren't comfortable using the command line, you can ask here or on Discord: https://ihaveahax.net/view/Discord
